######################
# cfgs for IMPACT KB #
######################

# args for network
network: resnet34
net_avgpool_size: 7
net_sobel: True
net_heads:
  - 20
  - 7

# args for dataset and dataloader
dataset: image_folder_wrapper
data_root: ./data/HDI_balanced_112
tfm_means: (0.485, 0.456, 0.406)
tfm_stds: (0.229, 0.224, 0.225)
tfm_size: (96, 96)
tfm_resize: 112

# smaller batch size for lower memory consumption
batch_size: 64
num_workers: 4
max_epochs: 200

session: balanced_112
