######################
# cfgs for IMPACT KB #
######################

# args for network
network: resnet34standard
net_sobel: False
net_heads:
#  - 30
  - 10

# args for dataset and dataloader
dataset: image_folder_wrapper
data_root: ./data/tobacco3482
tfm_means: (0.485, 0.456, 0.406)
tfm_stds: (0.229, 0.224, 0.225)
tfm_size: (224, 224)
tfm_resize: 240

# smaller batch size for lower memory consumption
batch_size: 64
num_workers: 4
max_epochs: 200

pica_target: (0.07, 0.17, 0.12, 0.16, 0.18, 0.05, 0.06, 0.08, 0.04, 0.08)

session: tobacco3482_xe
