######################
# cfgs for IMPACT KB #
######################

# args for network
net_heads:
  - 12
  - 4

# args for dataset and dataloader
dataset: impact_kb
data_root: ./data/IMPACT_KB
tfm_means: (0.485, 0.456, 0.406)
tfm_stds: (0.229, 0.224, 0.225)
tfm_size: (224, 224)
tfm_resize: 240

# smaller batch size for lower memory consumption
batch_size: 32
